name: senger
description: A messaging application

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.12.9
  permission_handler: ^3.2.1+1
  firebase_auth: '0.11.1+7'
  google_sign_in: 4.0.2
  shimmer:
  gradient_app_bar: ^0.0.1
  emoji_picker: ^0.1.0
  image_picker: ^0.6.3+1
  path_provider: ^1.6.0
  firebase_storage: ^3.1.1
  provider: ^4.0.4
  cached_network_image: ^2.2.0+1
  agora_rtc_engine: ^1.0.13
  simple_animations: ^1.3.3
  file_picker: ^1.13.0
  flutter_launcher_icons: ^0.7.0
  rxdart: ^0.24.1
  http: ^0.12.1
  flutter_local_notifications: ^1.4.4+1
  # local storage
  hive: ^1.4.1+1
  sqflite: ^1.3.0

  # intl
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/logo.png"
  android: true

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
